_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
learning_rate:
    value: 1e-05
model:
    value: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
num_iterations:
    value: 100
num_samples:
    value: 1000
